- name: Update Caddy service (ExecStart)
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/caddy.service
    line: ExecStart=/usr/bin/caddy run --environ --config {{ hub_persistent_volume_path }}/caddy/Caddyfile
    regexp: "^ExecStart="

- name: Update Caddy service (ExecRestart)
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/caddy.service
    line: ExecReload=/usr/bin/caddy reload --config {{ hub_persistent_volume_path }}/caddy/Caddyfile --force
    regexp: "^ExecReload="

- name: Ensure caddy folder exist in persistent
  ansible.builtin.file:
    path: "{{ hub_persistent_volume_path }}/caddy"
    state: directory
    owner: caddy
    group: caddy

- name: Ensure caddy storage folder exist in persistent
  ansible.builtin.file:
    path: "{{ hub_persistent_volume_path }}/caddy/storage"
    state: directory
    owner: caddy
    group: caddy

- name: Push Caddy config file
  ansible.builtin.template:
    src: "caddy/Caddyfile.j2"
    dest: "{{ hub_persistent_volume_path }}/caddy/Caddyfile"
    owner: caddy
    group: caddy
    mode: '0600'

- name: Start Caddy service
  ansible.builtin.systemd_service:
    name: caddy.service
    daemon_reload: true
    enabled: true
    state: restarted