- name: Ensure hub folder exist in persistent exist
  ansible.builtin.file:
    path: "{{ hub_persistent_volume_path }}/hub"
    state: directory
    owner: jupyterhub
    group: jupyterhub

- name: Push systemd env file
  ansible.builtin.template:
    src: "systemd/jupyterhub.env.j2"
    dest: "{{ hub_persistent_volume_path }}/hub/.env"
    owner: jupyterhub
    group: jupyterhub
    mode: '0600'

- name: Push jupyterhub config file
  ansible.builtin.copy:
    src: "jupyterhub.py"
    dest: "{{ hub_persistent_volume_path }}/hub/jupyterhub.py"
    owner: jupyterhub
    group: jupyterhub
    mode: '0600'

- name: Ensure custom folder exist 
  ansible.builtin.file:
    path: "{{ hub_persistent_volume_path }}/hub/hub_customs"
    state: directory
    owner: jupyterhub
    group: jupyterhub

- name: Copy jupytercloud custom module 
  ansible.builtin.copy:
    src: jupytercloud_customs
    dest: "{{ hub_persistent_volume_path }}/hub/hub_customs/"
    state: directory
    owner: jupyterhub
    group: jupyterhub