- name: Add apt source for Caddy
  block:
    - name: Check GPG Key
      stat:
          path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      register: caddy_gpg_ok

    - name: Add Caddy GPG key
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        dest: /root/caddy-stable-archive-keyring.gpg.tmp
      when: not caddy_gpg_ok.stat.exists

    - name: Dearmor Caddy GPG Key
      ansible.builtin.shell:
        cmd: gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /root/caddy-stable-archive-keyring.gpg.tmp
      when: not caddy_gpg_ok.stat.exists

    - name: Add Caddy repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present
        filename: caddy

- name: Install Caddy
  ansible.builtin.apt:
      update_cache: yes
      name: caddy



